FROM node:16.16.0-alpine3.16

ARG TARGETPLATFORM

ENV CHROME_BIN="/usr/bin/chromium-browser" \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"

WORKDIR /home/node/app

COPY package*.json ./

RUN apk update && apk upgrade
RUN apk add --no-cache python3 make g++
RUN if [ "$TARGETPLATFORM" != "linux/arm/v7" ]; then apk add --no-cache udev ttf-freefont chromium; fi
RUN npm install -g npm@8.14.0
RUN npm install
RUN npm install pm2 -g

COPY . .

EXPOSE 3333

CMD [ "pm2-runtime", "start", "ecosystem.config.js" ]
