name: AdonisJs CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [18.x]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Adonis dependencies
        run: npm install
      - name: Install Vue dependencies
        run: cd ui && npm install --legacy-peer-deps
      - name: Install legacy peer dependencies
        run: npm install --legacy-peer-deps
      - name: Update version
        run: echo VERSION=$(node -p "require('./package.json').version") >> $GITHUB_ENV
      - name: Build
        run: npm run build
      - name: Display version name
        run: echo {{ env.VERSION }}
      - name: Change directory
        run: cd build
      - name: Create container
        run: |
          cd build
          docker buildx create --name mybuilder --driver docker-container --bootstrap --use
      - name: Build an push container
        run: |
          cd build
          echo ${{ secrets.TOKEN }} | docker login ghcr.io -u hexa-ai --password-stdin
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --push --file dockerfile-hd -t ghcr.io/hexa-ai/hexa-data:${{ env.VERSION }} -t ghcr.io/hexa-ai/hexa-data:latest .
