name: AdonisJs CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        redis-version: [6]
    services:
      redis:
        image: redis:6
        ports:
          - "6379:6379" # Map Redis container port to the host machine
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Adonis dependencies
        run: npm install
      - name: Install Vue dependencies
        run: cd ui && npm install --legacy-peer-deps
      - name: Setup database
        run: mkdir tmp && touch tmp/db.sqlite3
      - name: Run tests
        run: node -r @adonisjs/assembler/build/register japaFile.ts -ci
        env:
          REDIS_HOST: redis
